swagger: '2.0'
info:
  version: "0.1.0"
  title: "Books - SS-Octopus"
basePath: /
produces:
  - application/json
paths:
  /books:
    get:
      summary: Returns a list of Books
      description: Gets `Book` objects.
      tags:
        - Book
      produces:
        - application/json
      responses:
        200:
          description: A list of `Book` recordss
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'
        204:
          description: No content
        404:
          description: Not Found
definitions:
  Book:
    properties:
      id:
        type: string
        format: UUID
        description: Unique id of a `Book`
        x-chance-type: guid
      title:
        type: string
        description: title of a `Book`
        x-chance-type: word
      pages:
        description: page count of `Book`
        type: integer
        format: int64
        x-type-options:
          min: 50
          max: 2000


